name: slomore
adopt-info: slomore
summary: A custom pager that outputs lines with a delay, allowing control over pacing.
description: |
  A custom pager that outputs lines with a delay, allowing control over pacing.

license: MIT

base: core24
grade: stable
confinement: strict
compression: lzo
issues: https://github.com/popey/slomore/issues
source-code: https://github.com/popey/slomore
contact: https://github.com/popey/slomore

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
  armhf:
    build-on: [armhf]
    build-for: [armhf]
  ppc64el:
    build-on: [ppc64el]
    build-for: [ppc64el]
  s390x:
    build-on: [s390x]
    build-for: [s390x]

apps: 
  slomore:
    command: bin/slomore
      
parts:
  slomore:
    source: https://github.com/popey/slomore
    source-type: git
    plugin: rust
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)" 
      
    build-packages:
      - rustc
      - cargo
